title: Hello, welcome to my website!
theme: jekyll-theme-cayman
descriptions: 
collections:
  projects:
    output: true
    
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
