title: Ianjon Brower's Resume
theme: jekyll-theme-cayman
descriptions:
collections:
  projects:
    output: true
    
defaults:
  - scope:
      path: "_projects"
      type: 
    values:
      layout: page
