title: Ianjon Brower's Resume
theme: jekyll-theme-cayman
descriptions:
collections:
  projects:
    output: true
    
defaults:
  - scope:
      path: ""
      type: _projects
    values:
      layout: page
