title: Ianjon Brower's Resume
theme: jekyll-theme-cayman
descriptions: [Some projects I've helped with](https://ianjon.github.io/what/)
collections:
  projects:
    output: true
    
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
