title: ![Click here for a list of projects i've done/helped with](ianjon.github.io/projects/) 
theme: jekyll-theme-cayman
descriptions: 
collections:
  projects:
    output: true
    
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
